import Foundation

enum ExerciseLibrary {
    static let all: [String] = [
        "Barbell Row",
        "Bench Press",
        "Bicep Curl",
        "Bulgarian Split Squat",
        "Cable Row",
        "Calf Raise",
        "Chest Fly",
        "Crunch",
        "Deadlift",
        "Dip",
        "Face Pull",
        "Front Raise",
        "Glute Bridge",
        "Hammer Curl",
        "Hip Thrust",
        "Incline Bench Press",
        "Cable Kickback",
        "Lat Pulldown",
        "Lateral Raise",
        "Leg Curl",
        "Leg Extension",
        "Leg Press",
        "Leg Raise",
        "Lunge",
        "Overhead Press",
        "Plank",
        "Pull-Up",
        "Push-Up",
        "Romanian Deadlift",
        "Russian Twist",
        "Seated Row",
        "Skull Crusher",
        "Squat",
        "Sumo Deadlift",
        "Tricep Extension",
        "Upright Row",
    ]
}
